### ISSUE TITLE
Filter error using game_solve function

### ISSUE THREAD

**Issue by Alomes** [skranz/gtree#1]
I tried to run exactly the same code as the example：
`game %>%
      game_solve() %>%
     eq_outcomes() %>%
     select(eqo.ind,offer, accept, payoff_1, payoff_2)`
and ran into the error 
`#Error in filter(df, all.contained) : object 'all.contained' not found`
Tracing back to find where it is from, I got
```
> lifecycle::last_lifecycle_warnings()
[[1]]
<warning/lifecycle_warning_deprecated>
Warning:
`summarise_()` was deprecated in dplyr 0.7.0.
ℹ Please use `summarise()` instead.
ℹ The deprecated feature was likely used in the dplyr package.
  Please report the issue at
  <https://github.com/tidyverse/dplyr/issues>.
---
Backtrace:
 1. gtree::game_gambit_solve(game)
 2. gtree::gambit.solve.eq(...)
 3. gtree::tg.to.efg(tg, file.with.dir = efg.file.with.dir, verbose = verbose)
 4. gtree::action.level.to.gambit.txt(lev, oco.df)
 7. dplyr::summarise_(...)
 8. dplyr:::lazy_deprec("summarise", hint = FALSE)
```
Then I found the function `gtree::action.level.to.gambit.txt` indeed obtained the function `summarise_(...)`, using `trace(...)`.  But there‘s more to come.

The function `find.lev.descendant.info.sets` includes the following code:
```
function(...,subgames.only = TRUE,...){...,
  df = bind_rows(li)
  df = df %>% group_by(pinfo.set.ind) %>% mutate(all.contained = all(.contained))
  if (subgames.only) {
    df = filter(df, all.contained)
  }
}
```
assumingly the source of the mentioned error report, because the `filter` is not from dplyr package but masked by other packages.

**Comment by Alomes** [comment]
1.

**Comment by skranz** [comment]
I checked it on my computer and did not get the error. (The deprecation warning should be addressed at some point but that does not seem to cause the problem.)  Perhaps you have loaded another package not neccessary for gtree that overwrites the `filter` function?
